version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: >
      sh -c "
      python /app/ShopApi/manage.py migrate &&
      python /app/ShopApi/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True

  redis:
    image: redis:7.2.5
    container_name: redis_server
    ports:
      - "6379:6379"
